version: '3.7'

networks:
  bookie:

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodetest
      MYSQL_USER: root
      MYSQL_PASSWORD: netjer
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - bookie
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: netjer
      DB_DATABASE: nodetest
    depends_on:
      - mysql
    command: yarn dev
    ports:
      - "3000:3000"
    networks:
      - bookie

volumes:
  mysql: